controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    simplified.moveToRandomHoleOnGrid(myMole)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    info.changeScoreBy(0 + 1)
    simplified.moveToRandomHoleOnGrid(myMole)
    music.play(music.melodyPlayable(music.baDing), music.PlaybackMode.UntilDone)
    animation.runImageAnimation(
    my_Hammer,
    assets.animation`hammerAnimation`,
    50,
    false
    )
})
let my_Hammer: Sprite = null
let myMole: Sprite = null
game.showLongText("player1:use the arrow keys tomove the hammer player 2:pressa to move the mole", DialogLayout.Center)
info.setScore(0)
scene.setBackgroundImage(assets.image`grid`)
myMole = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . e e e e e e e e e e e e . . 
    . e e e e e e e e e e e e e e . 
    e e e e e e f e e f e e e e e e 
    e e e e e e f e e f e e e e e e 
    e e e e e e e e e e e e e e e e 
    e e e e f e e e e e e f e e e e 
    e e e e e f 3 3 3 3 f e e e e e 
    e e e e e e f 3 3 f e e e e e e 
    e e e e e f e e e e f e e e e e 
    e e e e e e e e e e e e e e e e 
    e e e f e e e e e e e e f e e e 
    e e e e f f f f f f f f e e e e 
    e e e e e e e e e e e e e e e e 
    e e e e e e e e e e e e e e e e 
    `, SpriteKind.Enemy)
my_Hammer = sprites.create(img`
    .................44.............
    ...............4422ee...........
    ...............4422ee...........
    .............4422eeeeee.........
    .............4422eeeeee.........
    ...........4422eeeeeeeeee.......
    ...........4422eeeeeeeeee.......
    .........4422eeeeeeeeeeeeee.....
    .........4422eeeeeeeeeeeeee.....
    ...........eeeeeeeeeeeeeeeeee...
    ...........eeeeeeeeeeeeeeeeee...
    .............eeeeeeeeeeeeee8866.
    .............eeeeeeeeeeeeee8866.
    .............ccddeeeeeeee8866...
    .............ccddeeeeeeee8866...
    ...........ccddbbeeeeee8866.....
    ...........ccddbbeeeeee8866.....
    .........ccddbb....ee8866.......
    .........ccddbb....ee8866.......
    .......ccddbb........66.........
    .......ccddbb........66.........
    .....ccddbb.....................
    .....ccddbb.....................
    ...ccddbb.......................
    ...ccddbb.......................
    .ccddbb.........................
    .ccddbb.........................
    .ddbb...........................
    .ddbb...........................
    ................................
    ................................
    ................................
    `, SpriteKind.Player)
simplified.moveOnlyOnscreenWithArrows(my_Hammer, simplified.Speeds.Fast)
carnival.startCountdownGame(15, carnival.WinTypes.Win)
carnival.addLabelTo("mole hunt", carnival.Areas.Bottom)
game.onUpdateInterval(1000, function () {
    simplified.moveToRandomHoleOnGrid(myMole)
})
